INSERT INTO NEWS (ID, FIRSTNAME, LASTNAME, AGE, BIRTHDATE, GENDER, HISTORY, DATE)
VALUES (nextval('NEWS_SEQ'), 'Kyle','Doe', 22,'1997-07-07','male','none', '2022-06-22');

INSERT INTO NEWS (ID, FIRSTNAME, LASTNAME, AGE, BIRTHDATE, GENDER, HISTORY, DATE)
VALUES (nextval('NEWS_SEQ'), 'Kyle','Doe', 22,'1997-07-07','male','none', '2022-06-22');

INSERT INTO NEWS (ID, FIRSTNAME, LASTNAME, AGE, BIRTHDATE, GENDER, HISTORY, DATE)
VALUES (nextval('NEWS_SEQ'), 'Kyle','Doe', 22,'1997-07-07','male','none', '2022-06-22');

INSERT INTO NEWS (ID, FIRSTNAME, LASTNAME, AGE, BIRTHDATE, GENDER, HISTORY, DATE)
VALUES (nextval('NEWS_SEQ'), 'Kyle','Doe', 22,'1997-07-07','male','none', '2022-06-22');

INSERT INTO NEWS (ID, FIRSTNAME, LASTNAME, AGE, BIRTHDATE, GENDER, HISTORY, DATE)
VALUES (nextval('NEWS_SEQ'), 'Kyle','Doe', 22,'1997-07-07','male','none', '2022-06-22');


INSERT INTO NEWS (ID, FIRSTNAME, LASTNAME, AGE, BIRTHDATE, GENDER, HISTORY, DATE)
VALUES (nextval('NEWS_SEQ'), 'Kyle','Doe', 22,'1997-07-07','male','none', '2022-06-22');



INSERT INTO SERVICES(ID, NAME, INFORMATION)
VALUES (nextval('SERVICES_SEQ'), 'Cell Surgery','click here');

INSERT INTO SERVICES(ID, NAME, INFORMATION)
VALUES (nextval('SERVICES_SEQ'), 'Nose Surgery','click me');

INSERT INTO SERVICES(ID, NAME, INFORMATION)
VALUES (nextval('SERVICES_SEQ'), 'Cell Therapy','click');

INSERT INTO SERVICES(ID, NAME, INFORMATION)
VALUES (nextval('SERVICES_SEQ'), 'Body Contouring','click');

INSERT INTO SERVICES(ID, NAME, INFORMATION)
VALUES (nextval('SERVICES_SEQ'), 'Facial Contouring','click');

INSERT INTO SERVICES(ID, NAME, INFORMATION)
VALUES (nextval('SERVICES_SEQ'), 'Anti-Aging','click');

INSERT INTO SERVICES(ID, NAME, INFORMATION)
VALUES (nextval('SERVICES_SEQ'), 'Anti-Aging','click');

INSERT INTO SERVICES(ID, NAME, INFORMATION)
VALUES (nextval('SERVICES_SEQ'), 'Anti-Aging','click');

INSERT INTO SERVICES(ID, NAME, INFORMATION)
VALUES (nextval('SERVICES_SEQ'), 'Anti-Aging','click');



